<?php

namespace Database\Seeders\PsikotestPaid\PapiKostick;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class QuestionPapiKostickSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('question_papi_kosticks')->insert([
            [
                'id' => 1,
                'a' => 'Saya seorang pekerja keras',
                'b' => 'Saya bukan seorang pemurung',
                'created_at' => now(),
            ],
            [
                'id' => 2,
                'a' => 'Saya suka bekerja lebih baik dari orang lain',
                'b' => 'Saya suka menekuni pekerjaan yang saya lakukan sampai selesai',
                'created_at' => now(),
            ],
            [
                'id' => 3,
                'a' => 'Saya suka memperagakan kepada orang lain bagaimana cara melakukan sesuatu',
                'b' => 'Saya ingin bekerja sebaik mungkin',
                'created_at' => now(),
            ],
            [
                'id' => 4,
                'a' => 'Saya suka melakukan hal-hal yang lucu',
                'b' => 'Saya senang mengatakan kepada orang lain, apa yang harus dilakukannya',
                'created_at' => now(),
            ],
            [
                'id' => 5,
                'a' => 'Saya suka berkumpul dalam kelompok',
                'b' => 'Saya suka jika diperhatikan oleh orang lain',
                'created_at' => now(),
            ],
            [
                'id' => 6,
                'a' => 'Saya senang bersahabat intim',
                'b' => 'Saya suka berteman dalam suatu kelompok',
                'created_at' => now(),
            ],
            [
                'id' => 7,
                'a' => 'Saya cepat berubah jika saya rasa diperlukan',
                'b' => 'Saya berusaha untuk intim dengan teman-teman',
                'created_at' => now(),
            ],
            [
                'id' => 8,
                'a' => 'Saya suka membalas jika saya disakiti',
                'b' => 'Saya suka melakukan hal-hal yang baru dan berbeda',
                'created_at' => now(),
            ],
            [
                'id' => 9,
                'a' => 'Saya ingin agar atasan menyukai saya',
                'b' => 'Saya suka memberitahui orang lain jika mereka salah',
                'created_at' => now(),
            ],
            [
                'id' => 10,
                'a' => 'Saya suka mengikuti petunjuk-petunjuk yang diberikan pada saya',
                'b' => 'Saya suka menyenangkan atasan',
                'created_at' => now(),
            ],
            [
                'id' => 11,
                'a' => 'Saya berusaha bekerja “keras” (sekuat tenaga)',
                'b' => 'Saya seorang yang teratur. Saya menaruh semua barang pada tempatnya',
                'created_at' => now(),
            ],
            [
                'id' => 12,
                'a' => 'Saya dapat mempengaruhi orang lain untuk melakukan apa yang saya inginkan',
                'b' => 'Saya tidak mudah marah',
                'created_at' => now(),
            ],
            [
                'id' => 13,
                'a' => 'Saya suka memberitahukan kepada kelompok tentang apa yang harus mereka kerjakan',
                'b' => 'Saya selalu menekuni suatu pekerjaan sampai selesai',
                'created_at' => now(),
            ],
            [
                'id' => 14,
                'a' => 'Saya suka centil dan ingin diperhatikan',
                'b' => 'Saya ingin menjadi orang yang sangat berhasil',
                'created_at' => now(),
            ],
            [
                'id' => 15,
                'a' => 'Saya ingin sesuai dan diterima dalam kelompok',
                'b' => 'Saya suka membantu orang lain mengambil keputusan',
                'created_at' => now(),
            ],
            [
                'id' => 16,
                'a' => 'Saya cemas bila seseorang tidak menyukai saya',
                'b' => 'Saya suka bilang orang-orang memperhatikan saya',
                'created_at' => now(),
            ],
            [
                'id' => 17,
                'a' => 'Saya suka mencoba hal-hal yang baru',
                'b' => 'Saya lebih suka bekerja bersama orang lain daripada sendiri',
                'created_at' => now(),
            ],
            [
                'id' => 18,
                'a' => 'Saya kadang-kadang menyalahkan orang lain jika terjadi kesalahan',
                'b' => 'Saya merasa terganggu jika ada yang tidak menyukai saya',
                'created_at' => now(),
            ],
            [
                'id' => 19,
                'a' => 'Saya suka membiarkan bila orang lain mengatur saya',
                'b' => 'Saya suka mencoba pekerjaan-pekerjaan yang baru dan berbeda',
                'created_at' => now(),
            ],
            [
                'id' => 20,
                'a' => 'Saya menyukai petunjuk-petunjuk terperinci dalam menyelesaikan tugas',
                'b' => 'Bila saya terganggu oleh siapapun, saya akan memberitahukannya',
                'created_at' => now(),
            ],
            [
                'id' => 21,
                'a' => 'Saya selalu bekerja “keras”',
                'b' => 'Saya suka melaksanakan setiap langkah dengan teliti',
                'created_at' => now(),
            ],
            [
                'id' => 22,
                'a' => 'Saya akan menjadi seorang pemimpin yang baik',
                'b' => 'Saya dapat mengorganisir suatu pekerjaan dengan baik',
                'created_at' => now(),
            ],
            [
                'id' => 23,
                'a' => 'Saya mudah tersinggung',
                'b' => 'Saya lambat dalam membuat keputusan',
                'created_at' => now(),
            ],
            [
                'id' => 24,
                'a' => 'Saya suka mengerjakan beberapa pekerjaan sekaligus',
                'b' => 'Bila saya berada dalam suatu kelompok saya suka berdiam diri',
                'created_at' => now(),
            ],
            [
                'id' => 25,
                'a' => 'Saya senang bila diundang',
                'b' => 'Saya ingin lebih baik dari yang lain dalam mengerjakan sesuatu',
                'created_at' => now(),
            ],
            [
                'id' => 26,
                'a' => 'Saya suka berteman secara intim',
                'b' => 'Saya suka menasehati orang lain',
                'created_at' => now(),
            ],
            [
                'id' => 27,
                'a' => 'Saya suka melakukan hal-hal yang baru dan berbeda',
                'b' => 'Saya suka menceritakan bagaimana saya berhasil melakukan sesuatu',
                'created_at' => now(),
            ],
            [
                'id' => 28,
                'a' => 'Bila saya benar, saya suka mempertahankannya',
                'b' => 'Saya ingin diterima dan diakui dalam suatu kelompok',
                'created_at' => now(),
            ],
            [
                'id' => 29,
                'a' => 'Saya tidak mau berbeda dengan orang lain',
                'b' => 'Saya berusaha untuk sangat intim dengan orang lain',
                'created_at' => now(),
            ],
            [
                'id' => 30,
                'a' => 'Saya senang diberitahu bagaimana melakukan sesuatu pekerjaan',
                'b' => 'Saya mudah bosan',
                'created_at' => now(),
            ],
            [
                'id' => 31,
                'a' => 'Saya bekerja “keras”',
                'b' => 'Saya banyak berpikir dan berencana',
                'created_at' => now(),
            ],
            [
                'id' => 32,
                'a' => 'Saya memimpin kelompok',
                'b' => 'Hal-hal kecil (detail) menarik bagi saya',
                'created_at' => now(),
            ],
            [
                'id' => 33,
                'a' => 'Saya dapat mengambil keputusan secara mudah dan tepat',
                'b' => 'Saya menyimpan barang-barang saya secara rapih dan teratur',
                'created_at' => now(),
            ],
            [
                'id' => 34,
                'a' => 'Saya cepat dalam melaksanakan suatu pekerjaan',
                'b' => 'Saya tidak sering marah atau sedih',
                'created_at' => now(),
            ],
            [
                'id' => 35,
                'a' => 'Saya ingin menjadi bagian dari kelompok',
                'b' => 'Saya hanya ingin melakukan satu pekerjaan pada suatu saat',
                'created_at' => now(),
            ],
            [
                'id' => 36,
                'a' => 'Saya berusaha untuk intim dengan teman-teman saya',
                'b' => 'Saya berusaha keras menjadi yang terbaik',
                'created_at' => now(),
            ],
            [
                'id' => 37,
                'a' => 'Saya suka mode terbaru untuk pakaian dan mobil',
                'b' => 'Saya suka bertanggungjawab bagi orang lain',
                'created_at' => now(),
            ],
            [
                'id' => 38,
                'a' => 'Saya menyukai perdebatan',
                'b' => 'Saya suka mendapat perhatian',
                'created_at' => now(),
            ],
            [
                'id' => 39,
                'a' => 'Saya senang diatur oleh orang lain',
                'b' => 'Saya tertarik menjadi bagian dari kelompok',
                'created_at' => now(),
            ],
            [
                'id' => 40,
                'a' => 'Saya suka mengikuti peraturan dengan hati-hati',
                'b' => 'Saya suka orang mengenal saya dengan baik',
                'created_at' => now(),
            ],
            [
                'id' => 41,
                'a' => 'Saya bekerja sangat “keras”',
                'b' => 'Saya mempunyai sifat bersahabat',
                'created_at' => now(),
            ],
            [
                'id' => 42,
                'a' => 'Orang lain beranggapan bahwa saya adalah seorang pemimpin yang baik',
                'b' => 'Saya berpikir panjan dan berhati-hati',
                'created_at' => now(),
            ],
            [
                'id' => 43,
                'a' => 'Saya sering mengambil kesempatan',
                'b' => 'Saya senang mengurus hal-hal kecil',
                'created_at' => now(),
            ],
            [
                'id' => 44,
                'a' => 'Orang berpendapat bahwa saya bekerja cepat',
                'b' => 'Orang berpendapat bahwa saya rapi dan teratur',
                'created_at' => now(),
            ],
            [
                'id' => 45,
                'a' => 'Saya senang permainan-permainan dan berolahraga',
                'b' => 'Saya mempunyai pribadi yang menyenangkan',
                'created_at' => now(),
            ],
            [
                'id' => 46,
                'a' => 'Saya senang bila orang lain bersikap intim dan bersahabat',
                'b' => 'Saya selalu berusaha untuk menyelesaikan sesuatu yang telah saya mulai',
                'created_at' => now(),
            ],
            [
                'id' => 47,
                'a' => 'Saya senang bereksperimen dan mencoba hal-hal baru',
                'b' => 'Saya suka melaksanakan suatu pekerjaan sulit dengan baik',
                'created_at' => now(),
            ],
            [
                'id' => 48,
                'a' => 'Saya suka diperlakukan secara adil',
                'b' => 'Saya suka memberitahu orang lain bagaimana melaksanakan sesuatu',
                'created_at' => now(),
            ],
            [
                'id' => 49,
                'a' => 'Saya suka melakukan apa yang diharapkan dari saya',
                'b' => 'Saya suka menarik perhatian',
                'created_at' => now(),
            ],
            [
                'id' => 50,
                'a' => 'Saya suka petunjuk-petunjuk terperinci dalam melaksanakan suatu pekerjaan',
                'b' => 'Saya suka bertemu dengan orang lain',
                'created_at' => now(),
            ],
            [
                'id' => 51,
                'a' => 'Saya selalu berusaha menyelesaikan pekerjaan secara sempurna',
                'b' => 'Saya menganggap bahwa di dalam bekerja sehari-hari saya tidak mengenal lelah',
                'created_at' => now(),
            ],
            [
                'id' => 52,
                'a' => 'Saya adalah tipe seorang pemimpin',
                'b' => 'Saya mudah berteman',
                'created_at' => now(),
            ],
            [
                'id' => 53,
                'a' => 'Saya memanfaatkan peluang-peluang yang ada',
                'b' => 'Saya banyak sekali berpikir',
                'created_at' => now(),
            ],
            [
                'id' => 54,
                'a' => 'Saya bekerja dengan cara-cara yang selalu cepat',
                'b' => 'Saya senang bekerja dengan hal-hal kecil atau terperinci',
                'created_at' => now(),
            ],
            [
                'id' => 55,
                'a' => 'Saya mempunyai banyak tenaga untuk berolahraga',
                'b' => 'Saya suka mengatur dan menyimpan barang-barang secara rapi dan teratur',
                'created_at' => now(),
            ],
            [
                'id' => 56,
                'a' => 'Saya dapat bergaul baik dengan semua orang',
                'b' => 'Saya seorang yang “pandai mengendalikan diri”',
                'created_at' => now(),
            ],
            [
                'id' => 57,
                'a' => 'Saya ingin bertemu dengan orang-orang baru dan melakukan hal-hal baru',
                'b' => 'Saya selalu ingin menyelesaikan pekerjaan yang telah saya mulai',
                'created_at' => now(),
            ],
            [
                'id' => 58,
                'a' => 'Saya biasanya mempertahankan pendapat yang saya yakini',
                'b' => 'Saya biasanya suka bekerja “keras”',
                'created_at' => now(),
            ],
            [
                'id' => 59,
                'a' => 'Saya suka saran-saran dari orang yang saya kagumi',
                'b' => 'Saya suka diatur oleh orang lain',
                'created_at' => now(),
            ],
            [
                'id' => 60,
                'a' => 'Saya biarkan diri saya banyak dipengaruhi oleh orang lain',
                'b' => 'Saya suka jika mendapat banyak perhatian',
                'created_at' => now(),
            ],
            [
                'id' => 61,
                'a' => 'Saya biasanya bekerja sangat “keras”',
                'b' => 'Saya biasanya bekerja cepat',
                'created_at' => now(),
            ],
            [
                'id' => 62,
                'a' => 'Bila saya berbicara kelompok mendengarkan',
                'b' => 'Saya terampil menggunakan alat-alat kerja',
                'created_at' => now(),
            ],
            [
                'id' => 63,
                'a' => 'Saya lambat didalam pergaulan',
                'b' => 'Saya lambat dalam membuat keputusan',
                'created_at' => now(),
            ],
            [
                'id' => 64,
                'a' => 'Saya biasanya makan secara tepat',
                'b' => 'Saya suka membaca',
                'created_at' => now(),
            ],
            [
                'id' => 65,
                'a' => 'Saya suka ganti-ganti pekerjaan',
                'b' => 'Saya suka pekerjaan yang dilakukan dengan hati-hati',
                'created_at' => now(),
            ],
            [
                'id' => 66,
                'a' => 'Saya berteman sebanyak mungkin',
                'b' => 'Saya dapat menemukan kembali apa yang telah saya simpan',
                'created_at' => now(),
            ],
            [
                'id' => 67,
                'a' => 'Saya merencanakan jauh-jauh sebelumnya',
                'b' => 'Saya selalu menyenangkan',
                'created_at' => now(),
            ],
            [
                'id' => 68,
                'a' => 'Saya mempertahankan dengan bangga nama baik saya',
                'b' => 'Saya terus menekuni suatu masalah sampai selesai',
                'created_at' => now(),
            ],
            [
                'id' => 69,
                'a' => 'Saya tunduk kepada orang-orang yang saya kagumi',
                'b' => 'Saya ingin sukses',
                'created_at' => now(),
            ],
            [
                'id' => 70,
                'a' => 'Saya suka orang-orang lain yang membuat keputusan-keputusan kelompok',
                'b' => 'Saya suka membuat keputusan-keputusan untuk kelompok',
                'created_at' => now(),
            ],
            [
                'id' => 71,
                'a' => 'Saya selalu bekerja “keras”',
                'b' => 'Saya mengambil keputusan secara cepat dan mudah',
                'created_at' => now(),
            ],
            [
                'id' => 72,
                'a' => 'Kelompok biasanya melakukan apa yang saya inginkan',
                'b' => 'Saya biasanya bekerja cepat',
                'created_at' => now(),
            ],
            [
                'id' => 73,
                'a' => 'Saya sering merasa lelah',
                'b' => 'Saya lambat dalam mengambil keputusan',
                'created_at' => now(),
            ],
            [
                'id' => 74,
                'a' => 'Saya bekerja cepat',
                'b' => 'Saya mudah berteman',
                'created_at' => now(),
            ],
            [
                'id' => 75,
                'a' => 'Saya biasanya mempunyai gairah dan tenaga',
                'b' => 'Saya banyak menghabiskan waktu dengan berpikir',
                'created_at' => now(),
            ],
            [
                'id' => 76,
                'a' => 'Saya ramah terhadap orang',
                'b' => 'Saya suka pekerjaan yang memerlukan ketelitian',
                'created_at' => now(),
            ],
            [
                'id' => 77,
                'a' => 'Saya banyak berpikir dan berencana',
                'b' => 'Saya suka pekerjaan yang memerlukan ketelitian',
                'created_at' => now(),
            ],
            [
                'id' => 78,
                'a' => 'Saya suka pekerjaan yang menuntut hal-hal terperinci',
                'b' => 'Saya tidak mudah marah',
                'created_at' => now(),
            ],
            [
                'id' => 79,
                'a' => 'Saya suka mengikuti orang-orang yang saya kagumi',
                'b' => 'Saya selalu menyelesaikan pekerjaan yang telah saya mulai',
                'created_at' => now(),
            ],
            [
                'id' => 80,
                'a' => 'Saya suka petunjuk-petunjuk yang jelas',
                'b' => 'Saya suka bekerja “keras”',
                'created_at' => now(),
            ],
            [
                'id' => 81,
                'a' => 'Saya mengejar apa yang saya inginkan',
                'b' => 'Saya seorang pemimpin yang baik',
                'created_at' => now(),
            ],
            [
                'id' => 82,
                'a' => 'Saya dapat membuat orang lain bekerja keras',
                'b' => 'Saya adalah orang yang “senang hura-hura”',
                'created_at' => now(),
            ],
            [
                'id' => 83,
                'a' => 'Saya mengambil keputusan secara cepat',
                'b' => 'Saya berbicara dengan cepat',
                'created_at' => now(),
            ],
            [
                'id' => 84,
                'a' => 'Saya biasanya bekerja cepat',
                'b' => 'Saya berolahraga secara teratur',
                'created_at' => now(),
            ],
            [
                'id' => 85,
                'a' => 'Saya tidak suka bertemu dengan orang lain',
                'b' => 'Saya cepat merasa lelah',
                'created_at' => now(),
            ],
            [
                'id' => 86,
                'a' => 'Saya mempunyai banyak sekali teman',
                'b' => 'Saya banyak menghabiskan waktu dengan berpikir',
                'created_at' => now(),
            ],
            [
                'id' => 87,
                'a' => 'Saya suka bekerja dengan teori',
                'b' => 'Saya suka bekerja dengan hal-hal terperinci',
                'created_at' => now(),
            ],
            [
                'id' => 88,
                'a' => 'Saya suka bekerja dengan hal-hal terperinci',
                'b' => 'Saya suka mengorganisir pekerjaan saya',
                'created_at' => now(),
            ],
            [
                'id' => 89,
                'a' => 'Saya menaruh barang pada tempatnya',
                'b' => 'Saya selalu menyenangkan',
                'created_at' => now(),
            ],
            [
                'id' => 90,
                'a' => 'Saya suka diberitahu tentang apa yang perlu saya lakukan',
                'b' => 'Saya harus menyelesaikan apa yang saya mulai',
                'created_at' => now(),
            ],
        ]);
    }
}
