name: Auto Deploy on Push via SSH

on:
  push:
    branches:
      - development  # Ganti jika pakai branch lain

jobs:
  deploy:
    name: Pull changes from server
    runs-on: ubuntu-latest

    steps:
      - name: Connect to server and pull changes
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /home/berb9107/staging.berbinar.in
            git pull origin development
